[features]
seeds = true
skip-lint = false
[programs.devnet]
anchor_nft_staking = "AxJjgFUbaQn8ypKgRy56EKco2cQ95oGEN7oJUdo7VCUY"
loot_boxes = "E1QecFyDBGpRczaBjmQ7o2ry2wzAX1MgcrQQajroayWc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/swaroopmaddu/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
